---
subtitle: "PHIL343A -- Aesthetics"
title: "<font style='font-size:1em;'>🗓️ Week 03<br/> On Mimesis</font>"
author: Prof. [Reynolds](#)
institute: '[Stetson University](#)'
date: 02 September 2026
date-meta: 14 March 2023
date-format: "DD MMM YYYY"
toc: false
toc-depth: 1
toc-title: "Argument Forms, Formalization, Formation Rules:"
center-title-slide: false
from: markdown+emoji
format:
  revealjs:
    theme: moon
    fig-responsive: true
    slide-number: true
    incremental: true
    mouse-wheel: false
    preview-links: auto
    logo: /figures/icons/course_favicon.png
    css: /css/styles_slides.css
    footer: 'PHIL104Q -- Introduction to Logic'
---

# Books I-IV of Plato's Republic

* Justice in the ideal city and in the ideal soul
* The tripartite nature of the city and the soul

::: {.notes}
In the Republic, Plato tells a story. In the beginning of the story, Socrates, his mentor, is on his way back from the Piraeus after attending a religious festival. The Piraeuseans had recently imported a religious cult which worshiped the Tracian goddess Bendis. a question is raised. What is justice? Over time, varying accounts of justice are offered, each of which Socrates raises objections to (Bk I, 352d-354a). In order to explain his ideal of true justice, Socrates imagines the ideal city (BK IV, 434d-435a). This city is comprised of three classes of persons. Justice is achieved when each class, performs that role in the city, to which they are best suited. The working class is motivated by the pursuit of material wealth (558d-559c), the guardian class is motivated by honor (BK III, 414b), and the ruling class is motivated by truth (BK III, 412b-414b).

Accordingly, justice in the human soul, which is tripartite, is achieved when each part of the soul performs that role to which it is best suited. The appetites, perform those roles necessary for the base functions of the human person, food, procreation, and other necessary motor functions. The passions, or emotions are mobilized with respect to honor or respect, and its pursuit. Reason, which ought to rule over both the appetites and emotions, is concerned with an unyielding pursuit of truth.

:::

## The Artisans and the Poets

* What virtues belong to each class?
* What is the first class that Plato discusses?

::: {.notes}

Oddly enough, for Plato, art can disrupt this ideal ordering of the tripartite self. So now that we have looked at each of the necessary classes of the ideal city, what are their virtues? The organization of the varying selves of the soul can become disordered. Artists, most notably the poets, are often cited as teachers of virtue. Yet, the most they are capable of is imitation. Unlike other craftsmen, say a carpenter, the artist merely imitate what the craftsman makes. including virtue, as their *mere* opinions would lead them to believe of its nature. Imitation involves the mere imitation of craftmenship. First, there is the nature of a bed as created by say a god (X, 597b). In exercising their craft, the carpenter makes a bed, which is based on the original form of a bed. Though the craftman makes a bed, the ideal form of the bed is made by a god. A painter, finally then, exercises a different craft, and their resulting product, likewise differs from the god and the carpenter. Importantly here, while the god makes the form of the bed, and the carpenter makes an idealization fo this form, the painter, and other artists including poets, only imitate what the craftsmen makes. As such, the products of the artists are at a *third remove from the truth* (597e).

Importantly however, Plato's main target is not the imitation of objects, beds, tables, chairs, etc. Rather, Plato's primary target is the representation of virtue and other abstract constructs. Socrates and his student Plato, grew up on the narratives provided them by the Greek tragedians, poets, and other literary figures of their day. As pointed out by Martha @nuss86i, Greek tragedy of the sort that concerns Plato:

> shows good people being ruined because of things that just happen to them, things that they do not control. ... and ordinary fact of human life.

While Plato's concern is the existence of human virtue here, the above preoccupation does not express Plato's criticism fully. People do not typically loose their virtue because of some environmental catastrophe. The environment might obscure some important fact that contributed to the person's decision for instance, meaning the person involved might be excused in part because of ignorance. Additional, we often see great acts of courage, beneficence, selflessness in response to environment catastrophes. But, Greek tragedy did something else as well:

> Tragedy also ... shows good people doing bad things, things otherwise repugnant to their ethical character and commitments, because of circumstances whose origin does not lie with them.

These lie beyond simple ignorance. Here, the person is fully knowledgeable about what they are doing. They are not being physically or psychologically coerced. Rather, tragedy presents a character as being able to make one of two equally bad choices. The outcome of such stories, is for their audiences to question the nature of human goodness. What can possibly count as human virtue, virtue that is attributable to the person and not the environment?
:::
