# Is Star Citizen a Video Game?

## Fiction Functions

> Fictions have often been thought to provide opportunities for moral reflection or learning, and there is a large literature devoted to how (or indeed if) they can do this. But because of the interactive nature of videogame *fictions* - the player takes a part in the moral situations presented there, and whether or not the evil occurs is often up to them - the potential for th exploration of moral issues seems somehow more vivid: and perhaps more dangerous, where the game does not provide opportunities to put the content in a thoughtful or realistic context. [@tavi09, 9]

What should be explored?

* Definition of art, videogames
* What do artworks consist of (ontology), distinctions between other forms of art and videogames
* Their ability to express and the contents of these expressions, what are the effects of videogames in employing narratives, fictions and visual art?
* Our perceptions of their expressions, their appeal to our emotions
* The content and context of these expressions (narrative and interpretation), to our cognitions
* Those faculties which are involved in our appreciation of artworks, cognitive, emotional.
* Their moral significance
* Blame
* What is important about video games
* Are video games art?

## So what makes something a videogame?

> X is a videogame if it is an artifact in a visual digital medium, is intended as an object of entertainment, and is intended to provide such entertainment through the employment of one or both of the following modes of engagement: rule and objective gameplay or interactive fiction. [@tavi09, 26]


1. Must be an artifact in a visual digital medium.
2. Is intended as an object of entertainment
3. Is intended to provide entertainment through:
   1. rule and objective gameplay
   2. interactive fiction

## Some Definitions

By understanding what art is, we can understand our attempt to define videogames.

### What is a definition and what kinds are there?

#### Nominal: chart of the conceptual relations of words.

Consider variations of videogames, computer game, electronic game, console, PC, handheld etc. But this does not capture all of what we think of as a videogame.

#### Empirical or Essential

*Necessary and sufficient* conditions.

* Attempts to explain, clarify, or revise the "conceptual status of a  term.
* Attempts to capture the material "nature" of the object of definition.

### Narratological

### Ludological

### Interactive Fiction
