# A Treatise of Human Nature

* Rooted in his *A Treatise of Human Nature* (1739-40)

* Praise and Blame

* A science of human nature

Notable influences:

* Joseph Addison

* Francis Hutcheson

* Shaftesbury (Anthony Ashley Cooper).

>  So Hume’s reflections on aesthetics occupy a pivotal niche between the appearance of fine art theory and Kant’s defense of an independent aesthetic judgment in the Critique of Judgment – a defense clearly influenced by Kant’s reading of Hume’s essays and An Enquiry Concerning the Principles of Morals. [SEP](https://plato.stanford.edu/entries/hume-aesthetics/)

Hume retains the idea that the values within the scope of criticism are essentially pleasures of the human imagination.

In regards to the *fine arts*, these are reserved as a pleasure for those who can afford luxury.

* They consist of sensory and cognitive pleasures

From the older tradition, elegantly expounded by Addison in numerous essays written between 1709 and 1715, Hume retains the idea that the values within the scope of criticism are essentially pleasures of the human imagination.

But what are the values that are the subject of aesthetic judgment?
