---
subtitle: "PHIL343A -- Aesthetics"
title: "<font style='font-size:1em;'>🗓️ Week 05<br/> Aristotle's Poetics</font>"
author: Prof. [Reynolds](#)
institute: '[Stetson University](#)'
date: 02 September 2026
date-meta: 14 March 2023
date-format: "DD MMM YYYY"
toc: false
toc-depth: 1
toc-title: "The Art of Imitation:"
center-title-slide: false
from: markdown+emoji
format:
  revealjs:
    theme: moon
    fig-responsive: true
    slide-number: true
    incremental: true
    mouse-wheel: false
    auto-play-media: true
    preview-links: auto
    logo: /figures/icons/course_favicon.png
    css: /css/styles_slides.css
    footer: 'PHIL343A -- Aesthetics Aristotle'
---

* Earliest surviving work dedicated to art in the Western canon.

* Rediscovered by sixteenth-century Italian theorists.

  * Notable since other works of Aristotle were discovered first by Islamic philosophers during the early medieval ages.

* Originally written as a set of teaching notes and lecture materials for use in his academy.

* What is he doing in the Poetics and what is his motivation behind it?

---

* What is Aristotle's response to Plato's various critiques?

  * Religious

  * Moralistic

  * Psychological

  * Political

---

* First a member of Plato's academy, then founded his own: the Lyceum (335-23)

* The Poetics reflect a comprehensive, systematic, and analytic attempt to scrutinize in what would come to be known, Aristotelian, manner [Hallifex, 6].

* This manner begins with a definition of key terms, a large number of cross references which seek to make connections between the various tenets found in his texts.

---

* According to Steven hallifex, there are three essential elements to understanding Greek poetry.

## 1. Definitions

Defining poetry as a general category of representational arts, or mimesis. This category includes visual arts, poetry, music, and dancing.

## 2. Historical Precedent

The second recognition by Aristotle, is that Poetry has a history.

* A part of that history includes literary criticism, and literary history for instance.

* He views this history in the contexts of other cultural evolutionary markers such as the cultural evolution of tragedy and comedy.

* Mimesis, is an approach to art criticism which did not begin with Aristotle.

## 3. Establishing Genre Boundaries

The third element of this work includes the establishment and employment of genre.

* For Aristotle, genre is a scheme of enquiry that seeks to provide conditions through which mimetic concepts such as media, mimetic objects, and modes are delimited. In other words, he:

* Conditions

* Concepts

* Modes

---

> asserts the significance of formal design and unity for both the composition and the appreciation of literary works, and to offer a conception of artistic form which relates it to the organic forms crucial to his understanding of nature. [@hall95, 10; 50b34-51a6]

---

* Although we might call this approach 'formalist', a question arises about the necessity of genre concepts inferred in a particular mimetic example.

  * For instance, he references Plato's analysis of mimetic modes in Ch. III of this work.

  * However, for Aristotle, mimesis is an attempt to understand the broader world, by reference to the human propensity to represent human experiences through fictive representation, and imaginative reenactment.

  * In this way, Aristotle likely hopes to connect art to human nature as a capacity for human desire to understand universal concepts whether moral, religious, ethical, or relational.

---

# Mimesis, imitation

::: {.notes}

The way we begin to look at Aristotle's project, is by first understanding who his audience is and what they know.

There are several points here. First, his audience will likely be familiar with Plato. They will know something about his forms, his disdain for the artists, etc.

Next, they will likely be familiar with the artistic examples that Plato condemns. Perhaps however, they, much like us may have questions as to what his critique of these art forms actually were.

And as such, this is where we begin.

:::

## Poetry as a subject

Epic, Tragedy, Comedy, Dithyrambic, flute and lyre playing

Ilyliad, Odyssey, Metamorphosis, apparently "the mime of Sophron or Xenarchus". The works of Homer, Aeschylus, Sophocles, Empedocles. They would also have been familiar with Plato's works such as the *Phaedrus* and the *Symposium* for instance.

### First difference: Rhythm, language, harmony.

::: {.notes}

Harmony and rhythm by themselves correlate with flute and lyre playing. But imagine the lyre or flute without harmony or rhythm, e.g., imitative piping. It would seem that here, there is a difference in the object of representation, the object that is being represented. The way in which the object is represented, and the means through which it is represented.

There are three different possibilities with respect to imitation.

:::

# Means, Manner, and Object

## Means of Imitation

Rhythm but without harmony, drum and dance for instance.

Language without rhythm or harmony, speech and rhetoric. Or language with rhythm but not harmony.

<iframe width="560" height="315" src="https://www.youtube.com/embed/7Kt_Ym-SEF8?si=uI93aQ9QcrSymejy&amp;start=14" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

---

#### Imitative Piping

<iframe width="560" height="315" src="https://www.youtube.com/embed/Q3d7cKCyssA?si=lbvffxYTwdi5ayYu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

::: {.notes}

> Even if a theory of medicine or physical philosophy be put forth in a metrical form, it is usual to describe the writer in this way;

> There are, lastly, certain other arts, which combine all the means enumerated, rhythm, melody, and verse, e.g. Dithyrambic and Gnomic (verses of short characteristically wise sayings) poetry, Tragedy and Comedy;

Form vs. Content

How do we accurately depict life? What is the best way to tell a story?

This leads to the second difference . . .

:::

## Actions with respect to characters, good or bad.

1448a, What are the appropriate objects of representation, and what are the appropriate ways we should represent these objects? Good and bad men.

the character of the agent gives meaning to the action whether good or bad.

## The manner in which it is represented.

Narrative vs character, choose one, or represent dramatically.

### The three differences are means, objects, and manner.

## Imitation as Telos

> Imitation is natural to man from childhood, one of his advantages over the lower animals beings this, that he is the most imitative creature in the world.

He also delights in works of imitation.

* realistic representations, even if they go against our desires.

# Types

Epic poetry, tragedy, comedy, dithyrambic poetry, flute playing, lyre playing = modes of imitation

## The three main differences

Each type of poetry (art) differ from the other in three ways

1. Means of imitation

2. Objects of representation

3. Manner of their imitations

Is epic poetry denoted by 1, and 2, but not 3?

---

### A brief

> A combination of harmony and rhythm alone is the means in flute-playing and lyre-playing, and any other arts there may be of the same description, e.g. imitative piping. Rhythm alone, without harmony, is the means in the dancer's imitations; for even he, by the rhythms of his attitudes, may represent men's characters, as well as what they do and suffer.

## Species of Imitation

| | | Harmony | Rhythm | Language |
|---|---|---|---|---|
|  |  | Imitative Piping | Dance | Speech, Rhetoric |
| Harmony| Imitative Piping |  | flute-playing | |
| Rhythm | Dance | | | |
| Language | Speech, Rhetoric |  | | |

