# Imagination and the judgment of beauty

1. What is an aesthetic judgment?
2. What is a cognitive judgment?

Consider:

1. Understanding and Cognition
2. Pleasure and Imagination
3. 2 aligns with taste and judgments of taste are aesthetic.

Why? Two Concepts:

## The Quality of Beauty in two arguments

### First

> ***Taste*** is the faculty of judging an object or kind or representation through a satisfaction or dissatisfaction **without any interest**. The object of such a satisfaction is called beautiful. [159]

1. Analytic of the Beautiful 
2. Definition of the Beautiful
3. Universal beauty which is not conceptual
4. Beauty and the representation of purpose (conceptual)
5. Satisfying Objects

---

6. Beauty is conceptless and universal. (p. 159)
7. The beautiful, the agreeable (subjective aesthetic judgment) and the good. (p. 159)
8. Universal satisfaction of taste can be subjective (p. 160)
9. Pleasure does not proceed aesthetic judgment (p. 162)

## 10. 

> When we call something beautiful, the pleasure we feel is expected of everyone else in the judgment of taste as necessary, just as if it were to be regarded as a property of the object that is determined in it in accordance with concepts; but beauty is nothing by itself, without relation to the feeling of the subject. [p. 163]

# Second

> That is beautiful which pleases universally without a concept. [164]

## The Sublime

1. Judgments based on reflection
2. Quantify, quality, and modality
3. Perceptions and Conceptions
4. Normativity and Judgments of taste
5. Common human understanding (sensus communis)
6. Intellect and Beauty

---

7. Art
8. Art and Beauty
9. Art and nature
10. Artistic Talent
11. The nature of artistic talent
12. Judging someone to be artistically talented

## Analytic of the Beautiful

> But if the question is whether something is beautiful, one does not want to know whether there is anything that is, or that could be at stake for us, or for someone else, in the existence of the thing, but rather how we judge it in the mere contemplation (intuition or reflection). [156]

---

Judging that something is beautiful is objective.

1. Judgment of Taste
2. Non-subjective judgments
