# Books I-IV of Plato's Republic

* Justice in the ideal city and in the ideal soul
* The tripartite nature of the city and the soul

::: {.notes}
In the Republic, Plato tells a story. In the beginning of the story, Socrates, his mentor, is on his way back from the Piraeus after attending a religious festival. The Piraeuseans had recently imported a religious cult which worshiped the Tracian goddess Bendis. A question is raised. What is justice? Over time, varying accounts of justice are offered, each of which Socrates raises objections to (Bk I, 352d-354a). In order to explain his ideal of true justice, Socrates imagines the ideal city (BK IV, 434d-435a). This city is comprised of three classes of persons. Justice is achieved when each class, performs that role in the city, to which they are best suited. The working class is motivated by the pursuit of material wealth (558d-559c), the guardian class is motivated by honor (BK III, 414b), and the ruling class is motivated by truth (BK III, 412b-414b).

Accordingly, justice in the human soul, which is tripartite, is achieved when each part of the soul performs that role to which it is best suited. The appetites, perform those roles necessary for the base functions of the human person, food, procreation, and other necessary motor functions. The passions, or emotions are mobilized with respect to honor or respect, and its pursuit. Reason, which ought to rule over both the appetites and emotions, is concerned with an unyielding pursuit of truth.

:::

## The Artisans and the Poets

* What virtues belong to each class?
* What is the first class that Plato discusses?

::: {.notes}

Oddly enough, in Bk III, Plato leaves off any discussion of what he calls poetry, because even though he is convinced that poetry disrupts the training of the just sole, he cannot say how it does so until he has defined justice. This part of the project takes from Bk III to Bk IVX to do. While his conclusion is that art can disrupt this ideal ordering of the tripartite self, it is not until we get to Bk X to see how this is possible.

:::

::: {.notes}
Artists, most notably the poets, are often cited as teachers of virtue. Yet, the most they are capable of is imitation. This brings us to the primary argument in Bk X of the Republic. What is this class of thing which poetry belongs to?

:::

---

* What makes a good teacher of virtue?

* What makes a good poet?

::: {.notes}

Unlike other craftsmen, say a carpenter, the artist merely imitates what the craftsman makes, including virtue. But this is only as their *mere* opinions would lead them to believe of its nature. Imitation involves the mere imitation of craftsmanship. 

First, there is the nature of a bed as created by say a god (X, 597b). In exercising their craft, the carpenter makes a bed, which is based on the original form of a bed. Though the craftsman makes a bed, the ideal form of the bed is made by a god. A painter, finally then, exercises a different craft, and their resulting product, likewise differs from the god and the carpenter. 

Importantly here, while the god makes the form of the bed, and the carpenter makes an idealization of this form, the painter, and other artists including poets, only imitate what the craftsmen makes. As such, the products of the artists are at a *third remove from the truth* (597e).

:::

---

### What are the targets of artistic imitation?

* Classes of Objects
* What are their purposes?
* What are they made of?
* How do we understand them?

::: {.notes}

We are looking at a particular class of object. These are objects which are objects that are thought to represent other artifacts, namely those created by artisans.

Paintings, novels, stories, plays, films, and games. Consider Seurat's *Sunday on the Island of La Grande Jate*, or Dicken's *Tale of two Cities*, or Hitchcock's *North by Northwest*.

Kendall @walt90 in his book *Mimesis as Make-Believe*, defines the question nicely. These objects are important for our lives and culture. But what are they? What are they made of? How do they work? What purposes do they serve and how do they serve them? What means do they use to serve these purposes? How do people understand and appreciate them?

Walton will go on to argue that the kinds of objects that we refer to as mimetic, are best understood as props in games of make believe.
:::

### Representing Virtue and other uniquely human attributes

* Abstract Concepts
* What does Tragedy Represent?

::: {.notes}

Importantly however, Plato's main target is not the imitation of objects, beds, tables, chairs, etc. Rather, Plato's primary target is the representation of virtue and other abstract constructs. Socrates and his student Plato, grew up on the narratives provided them by the Greek tragedians, poets, and other literary figures of their day. As pointed out by Martha @nuss86i, Greek tragedy of the sort that concerns Plato:

What about the Sydney Opera House, paintings by Jason Pollack, or images created by game developers?

:::

---

### Tragedy Shows

> good people being ruined because of things that just happen to them, things that they do not control. ... and ordinary fact of human life. [@nuss86i]

::: {.notes}

While Plato's concern is the existence of human virtue here, the above preoccupation does not express Plato's criticism fully. People do not typically loose their virtue because of some environmental catastrophe. The environment might obscure some important fact that contributed to the person's decision for instance, meaning the person involved might be excused in part because of ignorance. Additional, we often see great acts of courage, beneficence, selflessness in response to environment catastrophes. But, Greek tragedy did something else as well:

:::

---

But . . .

* What is Vice?
* Vicious Action done in ignorance or something else?

::: {.incremental}

> Tragedy also ... shows good people doing bad things, things otherwise repugnant to their ethical character and commitments, because of circumstances whose origin does not lie with them.
:::

::: {.notes}

These lie beyond simple ignorance. Here, the person is fully knowledgeable about what they are doing. They are not being physically or psychologically coerced. Rather, tragedy presents a character as being able to make one of two equally bad choices. The outcome of such stories, is for their audiences to question the nature of human goodness. What can possibly count as human virtue, virtue that is attributable to the person and not the environment?

:::

## The skill of the poet and the skill of the moral educator

* If I lack, say the virtue of courage, but possess, say the virtue of painting, could I paint an accurate portrait of said virtue?
* If I possess, say the virtue of courage, but not the virtue of painting, could I paint an accurate portrait of said virtue?

> The reason is this: We hear some people say that poets know all crafts, all human affairs concerned with virtue and vice, and all about the gods as well. They say that if a good poet produces find poetry, he must have knowledge of the things he writes about, or else he wouldn't be able to produce it at all. [BK X, 598e]

::: {.notes}

1. Both the teacher of virtue and poet are skilled to some extent. To be skilled, you must first have certain abilities and knowledge. The question which remains is whether what one needs to know in order to be a good teacher of virtue is the same as what one needs to know to be a good poet.

Plato argues these are not analogous. What say you?

:::

---

Plato argues these are not analogous.

---

## What say you? {.center}
