# Paper

You are required to write one paper, which must be type-written, double-spaced, and eight to ten pages in length. Approximately four to six weeks before the paper is due, I will upload several essays to Canvas, and each student must choose ONE to which s/he will respond. If you wish to write a paper on a topic other than one of those suggested by me, you must clear it with me. (I will be more than happy to approve relevant topics.)

The papers you write are not opinion papers. It is standard practice among philosophers to view mere opinion to be worth less than the energy used to express it. What is worthwhile is a reasoned defense of one's opinion. Your paper should be written to present rational argument for the position which you hold.

Your paper should consist of two parts. The first part (4 to 5 pages) should be a short explication of the essay you have chosen.  This part should contain a statement of the author’s position, a statement of your own position (tell me whether you agree or disagree with the author) and an explanation of the author’s supporting arguments.  The second half of the paper should consist of your own evaluation or critique of the essay.  In this part of the paper, you should tell me WHY you agree or disagree with the author.  If you agree with the author, you should tell me what argument(s) are convincing.  Then tell me what argument(s) might be proffered by one who disagrees with the author and how the author might respond.  If you disagree with the author, you should provide criticism of the author’s essay and attempt to explain how the author might respond to the criticism.  Hence, whether you agree or disagree with the author, you should provide arguments against the author and responses thereto.  Finally, you should explain why you believe your position is the best position. You must NOT use outside sources for this essay.

***Late Policy:*** Your paper must be turned in by the end of class on the date that it is due. Five points will be deducted for every twenty-four-hour period when a paper is late. Thus, if a paper is turned in at 8:00 p.m. on the date that it is due, five points will be deducted. If a paper is turned in at 8:00 p.m. on the day following the day that it is due, ten points will be deducted. This policy is in effect so that diligent students are not penalized.
Due date for paper: All papers must be turned in by the end of class on Thursday, April 25th.
