# Stories suitable for a Guardian?

* What is it that Plato wants to ban from the Kallopolis?

::: {.notes}

Which professions are useful in the Kallopolis?

* Honor the gods, parents, and friendships (not take them lightly).

* Mitigate the fear of death.

* The more pleasant such stories are, the more convincing they will be.

* Censure comedy as well [388e].

* The stories should be truthful.

:::

## Useful In Plato's Kallopolis:

Lyre:

<iframe width="560" height="315" src="https://www.youtube.com/embed/baRvVPg6G1Y?si=y2A9pMmAhftxjYr5&amp;start=26" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

---

Cithara:

<iframe width="560" height="315" src="https://www.youtube.com/embed/YzLv-8ne88k?si=1DIZIXTJ6BY__sVI&amp;start=65" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

---

Useless:

<iframe width="560" height="315" src="https://www.youtube.com/embed/6zVgCvTWVBY?si=hS_pJODwD47Ob3Yu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Mixo-lydian

. . . also useless:

::: columns

::: {.column style="display:inline-block;width:40%;height:60%;border-radius:1em;margin:1%;padding:1.5%;background-color:#f5f5f5"}

<iframe width="560" height="315" src="https://www.youtube.com/embed/Cok_vd48cA4?si=IX-t6gcSBkwkuMbq" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

:::

::: {.column style="width:50%;font-size:0.85em;margin-left:3%;"}

<li class="fragment"><span class="tag" style="background-color:var(--quarto-hl-st-color)">Freaking Useless</span></li>


:::

:::

---

Perhaps one of the best examples of the use of the Ionian mode:

Tuesday's Gone by Lynard Skynard:

<iframe width="560" height="315" src="https://www.youtube.com/embed/lSk9Ri1z1S8?si=CVeqDn4OBHyzzL-t&amp;start=19" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Dorian Mode:

> Just leave me the mode that would suitably imitate the tone and rhythm of a courageous person who is active in battle or doing other violent deeds, or who is failing and facing wounds, death, or some other misfortune, and who, in all these circumstances, is fighting off his fate steadily and with self-control.

---

Leave me also another mode, that of someone engaged in a peaceful, unforced, voluntary action, persuading someone or asking a favor of a god in prayer or of a human being through teaching and exhortation, or, on the other hand, of someone submitting to the supplications of another who is teaching him and trying to get him to change his mind, and who, in all these circumstances, is acting in moderation and self-control, not with arrogance but with understanding, and is content with the outcome. [399b]

## Like This:

<iframe width="560" height="315" src="https://www.youtube.com/embed/Tsb0oibEEqE?si=ATrdg7Kk-LnuW7Z7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## As seen in Jazz and Funk:

<iframe width="560" height="315" src="https://www.youtube.com/embed/khSrFHbP0DA?si=V9eCTXtJR3hIdkoA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## A favorite artist of mine,

Glad to see Plato would approve:

<iframe width="560" height="315" src="https://www.youtube.com/embed/ylXk1LBvIqU?si=htU4ABYVF_sTHXX6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

::: {.notes}

Example of Dorian mode.

But I do not think he would since Davis plays around with some of the changes.

~3:50, apparently, he plays 16 bars of Db, then 8 bars of Eb, then 8 bars of Db again.

:::

## And this:

Scarborough Fair

<iframe width="560" height="315" src="https://www.youtube.com/embed/RuqeA6nD0fI?si=TQFXFoe_GMfuZ6hn" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

::: {.notes}

> If our young people, Adeimantus, listen to these stories without ridiculing them as not worth hearing, it's hardly likely that they'll consider the things described in them to be unworthy or mere human beings like themselves or that they'll rebuke themselves for doing or saying similar things when misfortune strikes. Instead, they'll feel neither shame nor restraint but groan and lament at even insignificant misfortunes. [388d]
:::

## Appropriate Meter (Rhythm?)

<iframe width="560" height="315" src="https://www.youtube.com/embed/oYd7OSajpjA?si=iLVM0taCSvuT9q1m" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
