# Summa Theologiae (Theologica)

[A very Helpful Summary of Aquinas' views on happiness can be found here](https://philolibrary.crc.nd.edu/article/key-to-happiness/)

In the *Prologue* to the *Summa*, Thomas Aquinas mentions that he intends to write a brief introduction to the Christian religion for new converts. This turns into 4 *Parts* which include the Prima Pars (First Part), Prima Secundae Partis (First part of the second), Secundae Secundae Partis (Second Part of the Second), Tertiae Partis (Third Part).

Each part is divided into *Questions* which are further divided into *Articles*. Articles are divided into *Objections*, *On the Contrary*, *I answer that*, and *Replies to Objections (Responses)*.

We begin our readings in the first part of the second.

# Happiness 1st part, question 5

## The Key Concepts here Include: {.smaller}

***Man's Final End*** – The ultimate goal of all human life. All of our other goals are chosen for the sake of this final end.

***Highest Good*** – The greatest good for a human being.

***Happiness*** – The final end and highest good of human life. The perfect good that objectively fulfills human nature and subjectively satisfies desire.

***Object of Happiness*** – The thing in which happiness essentially consists, the attainment of which will make us truly happy.

***Happiness Criteria*** – The conditions that the true object of happiness must satisfy. They are: finality, intrinsic value, purity, internality, authenticity, stability, self-sufficiency, completeness.a

## Articles

1. Can man attain happiness?

2. Can one man be happier than another?

3. Can man be happy in this life?

4. Can happiness be lost once it is attained?

5. Can happiness be attained through our own abilities?

6. Does man attain happiness through the actions of a higher creature?

7. Does man need to perform certain actions to attain happiness from God?

8. Does every man desire happiness?

To understand Aquinas' position on happiness, it first will help to understand his views on human nature.

Following Aristotle, Aquinas' view is teleological. This means that everything in nature has a purpose or end (telos) that it is directed towards.

This include:

* ends

* goals

* and purposes

::: {.notes}

But what are these and do we necessarily have access to them? The person who intends to rob a bank because it is enjoyable, is that person really pursuing the goal of robbery? Or is the goal something else? Is the goal of robbery really enjoyment? If so, then what is the goal of enjoyment? Is it pleasure? If so, then what is the goal of pleasure? Is it happiness? If so, then what is the goal of happiness?

:::

---

* What is their end?

* What is their purpose?

::: {.notes}
It would seem that what this example shows is that we can be mistaken about our ends, goals, and purposes.

:::

---

# Wealth

The first candidate for the object of happiness that Aquinas considers is wealth – money and possessions.

## Article 1

> I answer that, It is impossible for man’s happiness to consist in wealth. For wealth is twofold, as the Philosopher [Aristotle] says (Polit. i, 3), viz., natural and artificial. Natural wealth is that which serves man as a remedy for his natural wants, such as food, drink, clothing, carriages, dwellings, and such like; while artificial wealth is that which is not a direct help to nature, as money, but is invented by the art of man, for the convenience of exchange, and as a measure of things salable.

> Now it is evident that man’s happiness cannot consist in natural wealth. For wealth of this kind is sought for the sake of something else, viz., as a support of human nature. Consequently, it cannot be man’s last end, rather is it ordained to man as to its end. Wherefore in the order of nature, all such things are below man and made for him, according to Psalm 8: “Thou hast subjected all things under his feet.”

> And as to artificial wealth, it is not sought save for the sake of natural wealth, since man would not seek it except because, by its means, he procures for himself the necessaries of life. Consequently, much less can it be considered in the light of the last end. Therefore, it is impossible for happiness, which is the last end of man, to consist in wealth.

# Power

## Article 4

> On the contrary, Happiness is the perfect good. But power is most imperfect. For as Boethius says (De Consol. iii), “the power of man cannot relieve the gnawings of care, nor can it avoid the thorny path of anxiety.” And further on: “Think you a man is powerful who is surrounded by attendants, whom he inspires with fear indeed, but whom he fears still more?” Therefore, happiness does not consist in power.

> I answer that, It is impossible for happiness to consist in power; and this for two reasons. First because power has the nature of principle, as is stated in [Aristotle’s] Metaph. v, 12, whereas happiness has the nature of last end. Second, because power has relation to good and evil, whereas happiness is man’s proper and perfect good. Wherefore some happiness might consist in the good use of power, which is by virtue, rather than in power itself.

# Honor, Fame, and Glory

## Article 2

> On the contrary, Happiness is in the happy. But honor is not in the honored, but rather in him who honors, and who offers deference to the person honored, as the Philosopher says (Ethic. i, 5). Therefore, happiness does not consist in honor.

> I answer that, It is impossible for happiness to consist in honor. For honor is given to a man on account of some excellence in him; and consequently, it is a sign and attestation of the excellence that is in the person honored. Now a man’s excellence is in proportion, especially, to his happiness, which is man’s perfect good; and to its parts, i.e., those goods by which he has a certain share of happiness. And therefore honor can result from happiness, but happiness cannot principally consist therein.

## Article 3

> On the contrary, Happiness is man’s true good. But it happens that fame or glory is false: for as Boethius says (De Consol. iii), “many owe their renown to the lying reports spread among the people. Can anything be more shameful? For those who receive false fame, must needs blush at their own praise.” Therefore, man’s happiness does not consist in fame or glory. […]

> Reply to Objection 3: Fame has no stability; in fact, it is easily ruined by false report. And if sometimes it endures, this is by accident. But happiness endures of itself, and forever.

# Pleasure

In the second half of Question 2, Aquinas turns to internal goods, starting with pleasure or delight: pleasant experience, enjoyment, and having fun. Pleasure can take the form of either a bodily sensation (such as the taste of ice cream) or a mental attitude of taking pleasure in something (such as a job well done).



## Article 6

I answer that, […] in every thing, that which pertains to its essence is distinct from its proper accident: thus in man it is one thing that he is a mortal rational animal, and another that he is a risible animal. We must therefore consider that every delight is a proper accident resulting from happiness, or from some part of happiness; since the reason that a man is delighted is that he has some fitting good, either in reality, or in hope, or at least in memory […] Therefore, it is evident that neither is delight, which results from the perfect good, the very essence of happiness, but something resulting therefrom as its proper accident.

# Goods of the Body

## Article 5

I answer that, It is impossible for man’s happiness to consist in the goods of the body, and this for two reasons. First, because if a thing be ordained to another as to its end, its last end cannot consist in the preservation of its being. Hence a captain does not intend as a last end the preservation of the ship entrusted to him, since a ship is ordained to something else as its end, viz., to navigation. Now just as the ship is entrusted to the captain that he may steer its course, so man is given over to his will and reason, according to Ecclus. 15:14: “God made man from the beginning and left him in the hand of his own counsel.” Now it is evident that man is ordained to something as his end, since man is not the supreme good. Therefore, the last end of man’s reason and will cannot be the preservation of man’s being.

Second, because, granted [for the sake of argument] that the end of man’s will and reason be the preservation of man’s being, it could not be said that the end of man is some good of the body. For man’s being consists in soul and body; and though the being of the body depends on the soul, yet the being of the human soul depends not on the body, as shown above [ST I, q. 75, a. 2]; and the very body is for the soul, as matter for its form, and the instruments for the man that puts them into motion, that by their means he may do his work. Wherefore all goods of the body are ordained to the goods of the soul, as to their end. Consequently, happiness, which is man’s last end, cannot consist in goods of the body.

# Goods of the Soul

## Article 7

I answer that, As stated above [ST I-II, q. 1, a. 8], the end is twofold: namely, the thing itself, which we desire to attain, and the use, namely, the attainment or possession of that thing. If, then, we speak of man’s last end as to the thing itself which we desire as last end, it is impossible for man’s last end to be the soul itself or something belonging to it. Because the soul, considered in itself, is as something existing in potentiality: for it becomes knowing actually from being potentially knowing, and actually virtuous from being potentially virtuous. Now since potentiality is for the sake of actuality as for its fulfillment, that which in itself is in potentiality cannot be the last end. Therefore, the soul itself cannot be its own last end.

In like manner neither can anything belonging to it, whether power, habit, or act. For that good which is the last end is the perfect good fulfilling the desire. Now man’s appetite, otherwise [known as] the will, is for the universal good. And any good inherent to the soul is a participated good, and consequently a portioned good. Therefore, none of them can be man’s last end.

# Any Created Good

## Article 8

It is impossible for any created good to constitute man’s happiness. For happiness is the perfect good, which lulls the appetite altogether; else it would not be the last end, if something yet remained to be desired. Now the object of the will, i.e., of man’s appetite, is the universal good; just as the object of the intellect is the universal true. Hence it is evident that naught can lull man’s will save the universal good. This is to be found, not in any creature, but in God alone, because every creature has goodness by participation. Wherefore God alone can satisfy the will of man, according to the words of Psalm 102: “Who satisfieth thy desire with good things.” Therefore, God alone constitutes man’s happiness.

# Stephen Wang

Wang-Aquinas on Human Happiness and the Natural Desire for God

1.	Humans crave happiness
2.	Perfect happiness can only be found in God
3.	God surpasses our very nature
4.	Therefore, we cannot achieve perfect happiness (paradox)

1.	Humans crave happiness
What are the ends of animals, plants? Can planetary bodies have an end? Aquinas’ view, following Aristotle is teleological, meaning he believes that all nature has some end to which it is perfected in. Think goal, purpose, final state, etc.
1.	Non-sentient objects
2.	Sentient objects (animals, etc)
3.	Human kind (rational beings)
Do non-rational beings crave happiness? Art 5 would seem to suggest that happiness only belongs to mankind. “Happiness consists in an operation of the speculative rather than of the practical intellect.”
a.	Highest operation, which is the intellect
b.	Highest object is the Divine Good
c.	Contemplation of Divine things is happiness (non-practical?)

2.	Perfect happiness can only be found in God
There are two kinds of goods.

